# Generated by Django 4.2.10 on 2026-03-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertracking',
            name='porter_order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='porter_tracking_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
