# Generated by Django 4.2.10 on 2026-03-10 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordertracking_porter_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertracking',
            name='porter_order_id',
        ),
        migrations.RemoveField(
            model_name='ordertracking',
            name='porter_tracking_url',
        ),
    ]
