[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = ["pip install -r ../requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "python manage.py migrate && gunicorn --workers 4 --worker-class sync --bind 0.0.0.0:$PORT --timeout 60 core.wsgi:application"
